In [ ]:
!pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

 pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

In [49]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport
import numpy as np
from sklearn.preprocessing import train

In [50]:
cd /content/drive/MyDrive/Work-/Linearregression/Admission/

[Errno 2] No such file or directory: '/content/drive/MyDrive/Work-/Linearregression/Admission/'
/content/drive/MyDrive/Work-/Linearregression/Admission


In [51]:
df = pd.read_csv('Admission_Prediction.csv')

In [52]:
df

Serial No.  GRE Score  TOEFL Score  ...  CGPA  Research  Chance of Admit
0             1      337.0        118.0  ...  9.65         1             0.92
1             2      324.0        107.0  ...  8.87         1             0.76
2             3        NaN        104.0  ...  8.00         1             0.72
3             4      322.0        110.0  ...  8.67         1             0.80
4             5      314.0        103.0  ...  8.21         0             0.65
..          ...        ...          ...  ...   ...       ...              ...
495         496      332.0        108.0  ...  9.02         1             0.87
496         497      337.0        117.0  ...  9.87         1             0.96
497         498      330.0        120.0  ...  9.56         1             0.93
498         499      312.0        103.0  ...  8.43         0             0.73
499         500      327.0        113.0  ...  9.04         0             0.84

[500 rows x 9 columns]

In [53]:
df_profile = ProfileReport(df)

In [54]:
df_profile.to_file("Admission.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [55]:
df_profile.to_notebook_iframe()

Output hidden; open in https://colab.research.google.com to view.

In [76]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge, Lasso, RidgeCV, LassoCV, ElasticNet, ElasticNetCV , LinearRegression 
import statsmodels.api as sm 
from sklearn.model_selection import train_test_split
import pandas.util.testing as tm
import matplotlib.pyplot as plt
import seaborn as sns 
sns.set()
%matplotlib inline

In [57]:
df 

Serial No.  GRE Score  TOEFL Score  ...  CGPA  Research  Chance of Admit
0             1      337.0        118.0  ...  9.65         1             0.92
1             2      324.0        107.0  ...  8.87         1             0.76
2             3        NaN        104.0  ...  8.00         1             0.72
3             4      322.0        110.0  ...  8.67         1             0.80
4             5      314.0        103.0  ...  8.21         0             0.65
..          ...        ...          ...  ...   ...       ...              ...
495         496      332.0        108.0  ...  9.02         1             0.87
496         497      337.0        117.0  ...  9.87         1             0.96
497         498      330.0        120.0  ...  9.56         1             0.93
498         499      312.0        103.0  ...  8.43         0             0.73
499         500      327.0        113.0  ...  9.04         0             0.84

[500 rows x 9 columns]

In [58]:
df["GRE Score"] = df['GRE Score'].fillna(df["GRE Score"].mean())

In [59]:
df.isnull().sum()

Serial No.            0
GRE Score             0
TOEFL Score          10
University Rating    15
SOP                   0
LOR                   0
CGPA                  0
Research              0
Chance of Admit       0
dtype: int64

In [60]:
df["TOEFL Score"] = df['TOEFL Score'].fillna(df["TOEFL Score"].mean())
df["University Rating"] = df['University Rating'].fillna(df["University Rating"].mean())

In [61]:
df.describe()

Serial No.   GRE Score  ...    Research  Chance of Admit
count  500.000000  500.000000  ...  500.000000        500.00000
mean   250.500000  316.558763  ...    0.560000          0.72174
std    144.481833   11.103952  ...    0.496884          0.14114
min      1.000000  290.000000  ...    0.000000          0.34000
25%    125.750000  309.000000  ...    0.000000          0.63000
50%    250.500000  316.558763  ...    1.000000          0.72000
75%    375.250000  324.000000  ...    1.000000          0.82000
max    500.000000  340.000000  ...    1.000000          0.97000

[8 rows x 9 columns]

In [62]:
df.drop(columns=["Serial No."], inplace = True )

In [63]:
df

GRE Score  TOEFL Score  ...  Research  Chance of Admit
0    337.000000        118.0  ...         1             0.92
1    324.000000        107.0  ...         1             0.76
2    316.558763        104.0  ...         1             0.72
3    322.000000        110.0  ...         1             0.80
4    314.000000        103.0  ...         0             0.65
..          ...          ...  ...       ...              ...
495  332.000000        108.0  ...         1             0.87
496  337.000000        117.0  ...         1             0.96
497  330.000000        120.0  ...         1             0.93
498  312.000000        103.0  ...         0             0.73
499  327.000000        113.0  ...         0             0.84

[500 rows x 8 columns]

In [64]:
y = df["Chance of Admit"] 
x = df.drop(["Chance of Admit"] , axis = 1)

In [65]:
x

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
0    337.000000        118.0                4.0  4.5  4.5  9.65         1
1    324.000000        107.0                4.0  4.0  4.5  8.87         1
2    316.558763        104.0                3.0  3.0  3.5  8.00         1
3    322.000000        110.0                3.0  3.5  2.5  8.67         1
4    314.000000        103.0                2.0  2.0  3.0  8.21         0
..          ...          ...                ...  ...  ...   ...       ...
495  332.000000        108.0                5.0  4.5  4.0  9.02         1
496  337.000000        117.0                5.0  5.0  5.0  9.87         1
497  330.000000        120.0                5.0  4.5  5.0  9.56         1
498  312.000000        103.0                4.0  4.0  5.0  8.43         0
499  327.000000        113.0                4.0  4.5  4.5  9.04         0

[500 rows x 7 columns]

In [66]:
scaler = StandardScaler()

In [67]:
arr = scaler.fit_transform(x)

In [68]:
df1 = pd.DataFrame(arr)

In [69]:
df1_pr = ProfileReport(df1)

In [70]:
df1_pr.to_notebook_iframe()

Output hidden; open in https://colab.research.google.com to view.

In [71]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [72]:
vif_df = pd.DataFrame()
vif_df["Feature"] = x.columns
vif_df['vif']= [ variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

In [74]:
vif_df

Feature       vif
0          GRE Score  4.153268
1        TOEFL Score  3.792866
2  University Rating  2.508768
3                SOP  2.775750
4                LOR  2.037308
5               CGPA  4.651670
6           Research  1.459311

In [109]:

x_train,x_test, y_train, y_test  = train_test_split(arr, y, test_size = 0.25, random_state =100)

In [110]:
x_test.shape

(125, 7)

In [111]:
model = LinearRegression()

In [112]:
model.fit(x_train,y_train)

LinearRegression()

In [113]:
model.coef_

array([0.015458  , 0.01908417, 0.00381077, 0.00315846, 0.01678637,
       0.07622763, 0.01400522])

In [114]:
model.intercept_

0.7181156002659718

In [115]:
pickle.dump(model, open("admission_lr_model.pickle", "wb"))

In [116]:
ls

Admission.html             Admission_perdict.ipynb   scaler.pickle
admission_lr_model.pickle  Admission_Prediction.csv


In [117]:
model.score(x_test,y_test)

0.8262844735686963

In [118]:
pickle.dump(scaler, open("scaler.pickle", "wb"))

In [119]:
sc = pickle.load(open("scaler.pickle", "rb"))

In [120]:
x = sc.fit_transform([[337,118,4,4.5,4.5,9.65,1]])
model.predict(x)

array([0.7181156])

In [121]:
df

GRE Score  TOEFL Score  ...  Research  Chance of Admit
0    337.000000        118.0  ...         1             0.92
1    324.000000        107.0  ...         1             0.76
2    316.558763        104.0  ...         1             0.72
3    322.000000        110.0  ...         1             0.80
4    314.000000        103.0  ...         0             0.65
..          ...          ...  ...       ...              ...
495  332.000000        108.0  ...         1             0.87
496  337.000000        117.0  ...         1             0.96
497  330.000000        120.0  ...         1             0.93
498  312.000000        103.0  ...         0             0.73
499  327.000000        113.0  ...         0             0.84

[500 rows x 8 columns]

In [122]:
pickle_model = pickle.load(open('admission_lr_model.pickle' , "rb"))

In [123]:
pickle_model.score(x_test,y_test)

0.8262844735686963

In [124]:
#calculate the adjusted r  score 
def adj_r2(x,y):
  r2 = pickle_model.score(x,y)
  n = x.shape[0]
  p = x.shape[1]
  adjusted_r = 1-(1-r2)*(n-1)/(n-p-1)
  return adjusted_r

In [125]:
adj_r2(x_test,y_test)

0.8158912369446012

In [126]:
model.coef_

array([0.015458  , 0.01908417, 0.00381077, 0.00315846, 0.01678637,
       0.07622763, 0.01400522])

In [127]:
model.intercept_

0.7181156002659718

In [140]:
lassocv = LassoCV(cv=5, max_iter = 200000000 , normalize = True )
lassocv.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Lasso())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * np.sqrt(n_samples). 
  FutureWarning,


LassoCV(cv=5, max_iter=200000000, normalize=True)

In [141]:
lassocv.alpha_

2.7745719225519405e-05

In [142]:
lasso = Lasso(alpha=lassocv.alpha_)
lasso.fit(x_train,y_train)

Lasso(alpha=2.7745719225519405e-05)

In [143]:
lasso.score(x_test,y_test)

0.826321706823379

In [148]:
ridgecv = RidgeCV(alphas = np.random.uniform(0,10,50) , cv = 10 , normalize = True )
ridgecv.fit(x_train,y_train)

Streaming output truncated to the last 5000 lines.
Set parameter alpha to: original_alpha * n_samples. 
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the d

RidgeCV(alphas=array([3.16919961, 0.52854832, 7.41039857, 7.87808458, 2.56792595,
       3.27693496, 5.58883519, 1.66682399, 3.64209543, 1.17305208,
       4.93653226, 6.30946442, 8.40304884, 6.58335027, 1.44648276,
       8.73079539, 3.98180699, 4.80707961, 4.74789968, 1.78717017,
       5.3083852 , 0.64573283, 3.88938735, 7.88932951, 0.02230555,
       1.53364861, 0.79393969, 2.08242509, 9.80774751, 3.76291451,
       8.6008212 , 5.7640552 , 5.73490848, 5.10418473, 8.30343114,
       2.36388168, 6.15050423, 7.56228144, 6.70999476, 0.55662311,
       9.14090797, 0.95992157, 7.13148329, 8.29321183, 4.26925144,
       8.5842366 , 5.07461755, 7.90120999, 2.94495194, 8.44975585]),
        cv=10, normalize=True)

In [150]:
ridgecv.alpha_

0.022305554486969914

In [151]:
ridge_lr = Ridge(alpha=ridgecv.alpha_)
ridge_lr.fit(x_train,y_train)

Ridge(alpha=0.022305554486969914)

In [155]:
ridge_lr.score(x_test,y_test)

0.8262920794080917

In [156]:
elastic = ElasticNetCV(alphas=  ela, cv= 10)
elastic.fit(x_train,y_train)

ElasticNetCV(cv=10)

In [158]:
elastic.alpha_

0.00032049828688228085

In [160]:
elastic.l1_ratio_

0.5

In [163]:
elastic_lr = ElasticNet(alpha= elastic.alpha_ , l1_ratio = elastic.l1_ratio_)
elastic_lr.fit(x_train,y_train)

ElasticNet(alpha=0.00032049828688228085)

In [164]:
elastic_lr.score(x_test,y_test)

0.8265118379982933